spring:
  profiles:
    active: h2, kafka-local

  application:
    name: smartcity-aggregated-data
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      airquality: sensor-airquality
      airquality-averages: sensor-airquality-averages
      replication-factor: 3
    streams:
      properties:
        auto.offset.reset: earliest
    properties:
      schema.registry.url: http://localhost:8091
    consumer:
      group-id: smartcity-averages

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      access: read_only
  metrics:
    enable:
      all: true
      kafka:
        streams: true
  prometheus:
    metrics:
      export:
        enabled: true
